### ISSUE TITLE
Files in samba share but services fail to run.

### ISSUE THREAD

**Issue by darkstar939** [ppamidimarri/TeslaCamMerge#10]
Files are in the samba share and are making it from the teslausb to the nano.  It appears the services keep failing.  Manually running LoadSSD.py transfers the files to /Footage without failure.  No logs to help troubleshoot.

systemctl status tcm-*
● tcm-loadSSD.service - Load SSD with dashcam clips received over CIFS share
   Loaded: loaded (/lib/systemd/system/tcm-loadSSD.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-02-07 19:25:23 AKST; 9s ago
  Process: 8422 ExecStart=/home/teslacam/TeslaCamMerge/LoadSSD.py (code=exited, status=1/FAILURE)
  Process: 8288 ExecStartPre=/bin/sleep 60 (code=exited, status=0/SUCCESS)
 Main PID: 8422 (code=exited, status=1/FAILURE)

● tcm-startFileBrowser.service - Start filebrowser with database in project path
   Loaded: loaded (/lib/systemd/system/tcm-startFileBrowser.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-02-07 19:25:21 AKST; 11s ago
  Process: 8391 ExecStart=/usr/local/bin/filebrowser -d /home/teslacam/filebrowser.db (code=exited, status=1/FAILURE)
  Process: 8274 ExecStartPre=/bin/sleep 60 (code=exited, status=0/SUCCESS)
 Main PID: 8391 (code=exited, status=1/FAILURE)

● tcm-removeOld.service - Remove old empty directories from CIFS share path
   Loaded: loaded (/lib/systemd/system/tcm-removeOld.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-02-07 19:25:24 AKST; 7s ago
  Process: 8427 ExecStart=/home/teslacam/TeslaCamMerge/RemoveOld.py (code=exited, status=1/FAILURE)
 Main PID: 8427 (code=exited, status=1/FAILURE)

● tcm-mergeTeslaCam.service - Merge Tesla dashcam videos from all three cameras
   Loaded: loaded (/lib/systemd/system/tcm-mergeTeslaCam.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-02-07 19:25:16 AKST; 16s ago
  Process: 8385 ExecStart=/home/teslacam/TeslaCamMerge/MergeTeslaCam.py (code=exited, status=1/FAILURE)
  Process: 8255 ExecStartPre=/bin/sleep 60 (code=exited, status=0/SUCCESS)
 Main PID: 8385 (code=exited, status=1/FAILURE)

Filebrowser also fails to load after reboot.  But will work if I use the command:

filebrowser -d /home/teslacam/filebrowser.db &

**Comment by ppamidimarri** [comment]
That's interesting. What's the LOG_LEVEL setting in TCMConstants.py? Try setting that to debug. Is the LOG_LOCATION available and writable to the user that the services are running as? Are the log files getting created and empty, or are they not getting created at all?

**Comment by darkstar939** [comment]
I tried debug both lower case and all caps.  No logs are being generated except file browser

**Comment by darkstar939** [comment]
So I completely set everything back up from scratch after first reboot of nano I get this.


Feb 10 12:55:28 nano systemd[1]: Starting Merge Tesla dashcam videos from all three cameras...

● tcm-removeOld.service - Remove old empty directories from CIFS share path
   Loaded: loaded (/lib/systemd/system/tcm-removeOld.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-02-10 12:55:29 AKST; 45s ago
  Process: 6248 ExecStart=/home/nano/TeslaCamMerge/RemoveOld.py (code=exited, status=115)
 Main PID: 6248 (code=exited, status=115)

Also I do have a question about your example TCMConstants.py file.

the example shows....

# Locations of the stored footage on the SSD. MUST include trailing /. PROJECT_USER must have read-write permissions on all these paths.
UPLOAD_LOCAL_PATH = '/home/pavan/Footage/Upload/'	# Any files placed in this directory will be uploaded to Google Drive
SSD_MOUNT_POINT = '/home/pavan'				# Mount point for the SSD

should SSD_MOUNT_POINT = '/home/userid/'  

have the trailing / or does that comment apply only to the upload local path?

**Comment by darkstar939** [comment]
disregard everything is good to go.  I started over from scratch with both nano and usb and everything is operational.  Great project thanks for sharing.  one question, since filebrowser is no longer an active project have you considered using something like tinyfilemanager or filestash as a replacement?
