### ISSUE TITLE
Server Side on regular Ubuntu Box

### ISSUE THREAD

**Issue by Helvio88** [ppamidimarri/TeslaCamMerge#11]
Hello!

Can the server side run on a standard Ubuntu Box instead of the Jetson? I already have a home server I'd like to use for this purpose. Thanks!

**Comment by ppamidimarri** [comment]
Yes, it should definitely work. As long as the Ubuntu box has the resources needed to run ffmpeg, you should be good to go.

**Comment by Helvio88** [comment]
Thanks! Got it to work!
