### ISSUE TITLE
Instruction to install filebrowser is out of date in section E

### ISSUE THREAD

**Issue by henroFall** [ppamidimarri/TeslaCamMerge#13]
Step E-3, at least, is wrong, with the instruction: `curl -fsSL https://filebrowser.org/get.sh | bash` .

This should be updated to `curl -fsSL https://raw.githubusercontent.com/filebrowser/get/master/get.sh | bash`

**Comment by ppamidimarri** [comment]
Thank you for the feedback, updated it.
