### ISSUE TITLE
Could you document the upgrade process?

### ISSUE THREAD

**Issue by henroFall** [ppamidimarri/TeslaCamMerge#16]
I see there have been some updates in the past few months, but I'm afraid to just copy files over without being sure that I'm not going to hose my installation. Is an upgrade process documented somewhere?

**Comment by ppamidimarri** [comment]
The only change in the last several months is to [TCMConstants.py](https://github.com/ppamidimarri/TeslaCamMerge/blob/master/TCMConstants.py) and it doesn't change anything that should break your installation. I would recommend merging any configuration changes you made to that file with the latest version from GitHub, and then restarting the services. Please backup your copy of TCMConstants.py first though.

**Comment by henroFall** [comment]
Thanks!
