### ISSUE TITLE
fail to merge

### ISSUE THREAD

**Issue by stepir** [ppamidimarri/TeslaCamMerge#6]
just noticed today:

2019-10-13 13:56:00,941 - MergeTeslaCam - ERROR - Error running ffmpeg command: /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.4*iw:h=0.4*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Full/2019-10-13_11-22-42-full.mp4, returncode: 1, stdout: b'', stderr: b'[Parsed_hstack_4 @ 0x5614ef483160] Input 1 height 288 does not match input 0 height 384.\n[Parsed_hstack_4 @ 0x5614ef483160] Failed to configure output pad on Parsed_hstack_4\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #2:0\n'

**Comment by stepir** [comment]
> 2019-10-13 13:56:00,941 - MergeTeslaCam - ERROR - Error running ffmpeg command: /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.4*iw:h=0.4*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Full/2019-10-13_11-22-42-full.mp4, returncode: 1, stdout: b'', stderr: b'[Parsed_hstack_4 @ 0x5614ef483160] Input 1 height 288 does not match input 0 height 384.\n[Parsed_hstack_4 @ 0x5614ef483160] Failed to configure output pad on Parsed_hstack_4\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #2:0\n'

**Comment by stepir** [comment]
`2019-10-13 13:56:00,941 - MergeTeslaCam - ERROR - Error running ffmpeg command: /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.4*iw:h=0.4*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Full/2019-10-13_11-22-42-full.mp4, returncode: 1, stdout: b'', stderr: b'[Parsed_hstack_4 @ 0x5614ef483160] Input 1 height 288 does not match input 0 height 384.\n[Parsed_hstack_4 @ 0x5614ef483160] Failed to configure output pad on Parsed_hstack_4\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #2:0\n'`

**Comment by stepir** [comment]
@ppamidimarri not sure if you are looking here - I've updated TeslaCamMerge to the latest and still have issues with the merge process?

`2019-10-14 17:25:19,303 - MergeTeslaCam - ERROR - Error running ffmpeg command: /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Full/2019-10-14_12-55-06-full.mp4 -vf "setpts=0.09*PTS" -c:v libx264 -crf 28 -profile:v main -tune fastdecode -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Fast/2019-10-14_12-55-06-fast.mp4, returncode: 1, stdout: b'', stderr: b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56536c510680] moov atom not found\n/.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Full/2019-10-14_12-55-06-full.mp4: Invalid data found when processing input\n'
2019-10-14 17:25:19,304 - MergeTeslaCam - INFO - Fast preview completed: 2019-10-14_12-55-06.`

**Comment by stepir** [comment]
here's the error if I manually try to run ffmpeg with that command:

`[Parsed_hstack_4 @ 0x557cc131ca60] Input 1 height 288 does not match input 0 height 384.
[Parsed_hstack_4 @ 0x557cc131ca60] Failed to configure output pad on Parsed_hstack_4
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #2:0                     `

**Comment by ppamidimarri** [comment]
That's weird. All four cameras (with v10, or 3 if you are on v9) should produce clips of the same dimensions. 

A few questions to help diagnose the problem:

- Is this happening with only one set of inputs, or with all of your clips? 
- What Tesla software version is your car on, v9 or v10?
- Was it working for you on v9, before you updated to the latest version?
- Did you try to view the four input files in a video viewer and see if they look ok?

**Comment by stepir** [comment]
hey

1) all can post logs
2) v10 latest 32.12.2
3) def yes no issue at all
4) yep even from filebrowser all ok

**Comment by stepir** [comment]
just checking now
- back is 1160x720
- front is 1280x960
- right is 1280x960
- left is 1280x960

**Comment by stepir** [comment]
it's a 2018 MX

**Comment by ppamidimarri** [comment]
OK may be on Model X, the back camera outputs with a smaller resolution. 

Try this command on the command line and see if it works: 

```
/usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Raw/2019-10-13_11-22-42-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.441*iw:h=0.533*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/SentryClips/Full/2019-10-13_11-22-42-full.mp4
```

If this works, I will add a variable in `TCMConstants.py` to set your car model so the merge works properly.

**Comment by stepir** [comment]
had to adjust a bit the paths but still error:

`admin@ubuntu_1804:~/TeslaCamMerge$ /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.441*iw:h=0.533*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Full/2019-10-13_11-22-42-full.mp4
[Parsed_hstack_4 @ 0x5622817d1f40] Input 1 height 383 does not match input 0 height 384.
[Parsed_hstack_4 @ 0x5622817d1f40] Failed to configure output pad on Parsed_hstack_4
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #2:0`

**Comment by stepir** [comment]
```
admin@ubuntu_1804:~/TeslaCamMerge$ /usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=0.441*iw:h=0.533*ih[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Full/2019-10-13_11-22-42-full.mp4
```

**Comment by ppamidimarri** [comment]
OK, let's try this: 

```
/usr/bin/ffmpeg -hide_banner -loglevel error -timelimit 9000 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-right_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-front.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-left_repeater.mp4 -i /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Download/SavedClips/2019-10-14_15-02-19/2019-10-14_15-01-45-back.mp4 -filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=512:h=384[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text='Oct 13\, 11\:22 AM':fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=5:x=(w-text_w)/2" -movflags +faststart -threads 0 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage/SavedClips/Full/2019-10-13_11-22-42-full.mp4
```

**Comment by stepir** [comment]
bingo

**Comment by ppamidimarri** [comment]
Great. I will fix this in the code and release it in a day or two. In the meanwhile, it you want to get it working, you do this:

1. Open `MergeTeslaCam.py` for edit
2. Go to line 20 and replace it with `ffmpeg_mid_full = '-filter_complex "[1:v]scale=w=1.2*iw:h=1.2*ih[top];[0:v]scale=w=0.4*iw:h=0.4*ih[right];[3:v]scale=w=512:h=384[back];[2:v]scale=w=0.4*iw:h=0.4*ih[left];[left][back][right]hstack=inputs=3[bottom];[top][bottom]vstack=inputs=2[full];[full]drawtext=text=\''`
3. Save the change
4. `sudo systemctl stop tcm-mergeTeslaCam`
5. `sudo systemctl start tcm-mergeTeslaCam`

**Comment by stepir** [comment]
Yep thanks already done it right away 😃

Can confirm event the automate process work smoothly now

Thanks!!!

**Comment by ppamidimarri** [comment]
This is now fixed.
