### ISSUE TITLE
fail to render stats.png

### ISSUE THREAD

**Issue by stepir** [ppamidimarri/TeslaCamMerge#7]
hey @ppamidimarri 

just noticed in the log the following:

```
22:30:56,588` - RemoveOld - ERROR - Error running cutycapt command export DISPLAY=:0 && /usr/bin/cutycapt --zoom-factor=1.5 --url=file:///.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.html --out=/.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png, returncode: 1, stdout: b'', stderr: b"QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-admin'\nNo protocol specified\nqt.qpa.screen: QXcbConnection: Could not connect to display :0\nCould not connect to any X display.\n"
```

Trying now to google for this error
```
QXcbConnection: Could not connect to display
```

**Comment by stepir** [comment]
```
admin@ubuntu_1804:~$ /usr/bin/cutycapt
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

Probably because I'm not using a jetson but a linux container on my qnap...

**Comment by stepir** [comment]
based on

https://askubuntu.com/questions/835292/running-cutycapt-from-php-on-my-ubunty-server

admin@ubuntu_1804:~$ sudo apt-get install xvfb

admin@ubuntu_1804:~$ xvfb-run --server-args="-screen 0, 1280x1200x24"  /usr/bin/cutycapt --zoom-factor=1.5 --url=file:///.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.html --out=/.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
admin@ubuntu_1804:~$ ll /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png
-rw-r--r-- 1 admin administrator 99211 Oct 15 22:56 /.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png       

gave an error but still produced the png :-)

**Comment by ppamidimarri** [comment]
Does the png have the correct picture? 

I will look into `xfvb-run` and see if it works for me instead of the `export DISPLAY=:0` command.

**Comment by stepir** [comment]
looks so. I'm trying to automate it now - yesterday night just tried by adding to the path of cutycapt in TCMconstants - but scripts still show errors, might need to change the code instead

**Comment by ppamidimarri** [comment]
Yeah, changing the path won't work. Change the code in `Stats.py` line 43, replace `export DISPLAY=:0 &&` with `xvfb-run --server-args=\"-screen 0, 1280x1200x24\" `

**Comment by stepir** [comment]
Thanks @ppamidimarri !!

can invoke manually by running stats.py? it's not producing an output and wondering if I can check a log? used to see logs into RemoveOld.log but seems to be logged only if being run when scheduled?

**Comment by ppamidimarri** [comment]
To run it manually, do `python3` at the command line, then `import Stats` and then `Stats.generate_stats_image()`. When you run it this way, the log is saved in a file called `.log` without any prefix.

**Comment by stepir** [comment]
modifying Stats.py in that way produce the following command 
```
/usr/bin/xvfb-run --server-args="-screen 0, 1280x1200x24" /usr/bin/cutycapt --zoom-factor=1.5 xvfb-run --server-args='-screen 0, 1280x1200x24' /usr/bin/cutycapt --zoom-factor=1.5 --url=file:///.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.html --out=/.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png
```

instead of

```
xvfb-run --server-args="-screen 0, 1280x1200x24"  /usr/bin/cutycapt --zoom-factor=1.5 --url=file:///.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.html --out=/.share/CACHEDEV1_DATA/Recordings/cc-eldiablo/Footage//stats.png
```

looking at the code now

**Comment by ppamidimarri** [comment]
This is now fixed.
